version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: infinity_agent_postgres
    environment:
      POSTGRES_DB: infinity_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always